vich_uploader:
    db_driver: orm

    mappings:
        cv_candidacy:
            uri_prefix: '%cv_candidacy%'
            upload_destination: '%kernel.project_dir%/public%cv_candidacy%'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
