vich_uploader:
    db_driver: orm

    mappings:
        cv_candidacy:
            uri_prefix: '%cv_candidacy%'
            upload_destination: '%kernel.project_dir%/public%cv_candidacy%'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
        spontaneous_candidacy:
            uri_prefix: '%spontaneous_candidacy%'
            upload_destination: '%kernel.project_dir%/public%spontaneous_candidacy%'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
        article_picture:
            uri_prefix: '%article_picture%'
            upload_destination: '%kernel.project_dir%/public%article_picture%'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer